name = "Compression test specimen parameters"
material = "Aluminum"
sample_numbers = [101, 105, 117, 125, 142]

[material_properties]
density = 2700  # kg/m3

[geometric_parameters]
diameter = 10e-3  # m
length = 30e-3  # Distance from the strain gage to the junction (m)

[oscilloscope_channels]
2 = "Input"
3 = "Intermediate"
4 = "Output"